# API配置文件
# 定义各个API的配置和启用状态

default_api: "pudu"

apis:
  pudu:
    enabled: true
    priority: 1
    config:
      base_url: "https://api.pudu.com"
      # 普渡API的其他配置参数
      
  gas:
    enabled: true
    priority: 2
    config:
      base_url: "https://openapi.gs-robot.com"
      client_id: "muryFD4sL4XsVanqsHwX"
      client_secret: "sWYjrp0D9X7gnkHLP727SeR5lJ1MFbUpOIumN6rt6tHwExvOOJk"
      open_access_key: "5d810a147b55ca9978afa82819b9625d"
      
  # 未来可以添加更多API
  # future_api:
  #   enabled: false
  #   priority: 3
  #   config:
  #     base_url: "https://api.future.com"
  #     api_key: "your_api_key"
