# credentials.example.yaml
# Copy this to credentials.yaml and fill in actual values
# IMPORTANT: Never commit credentials.yaml to version control

customers:
  # Customer with both Pudu and Gas robots
  customer_a:
    pudu:
      enabled: true
      api_app_key: "your_pudu_key_here"
      api_app_secret: "your_pudu_secret_here"
    gas:
      enabled: true
      client_id: "your_gas_client_id"
      client_secret: "your_gas_client_secret"
      open_access_key: "your_gas_access_key"
      base_url: "https://openapi.gs-robot.com"

  # Customer with only Pudu robots
  customer_b:
    pudu:
      enabled: true
      api_app_key: "customer_b_pudu_key"
      api_app_secret: "customer_b_pudu_secret"
    gas:
      enabled: false

  # Customer with only Gas robots
  customer_c:
    pudu:
      enabled: false
    gas:
      enabled: true
      client_id: "customer_c_gas_id"
      client_secret: "customer_c_gas_secret"
      open_access_key: "customer_c_gas_key"
      base_url: "https://openapi.gs-robot.com"

  # Default fallback credentials (for development/testing)
  default:
    pudu:
      enabled: true
      api_app_key: "APID18lGz1qBaBF9XWuttd5YszenrpsodKgt20i9"
      api_app_secret: "k2fmGdhz6mhqcl79eWot9f2kqoqosC2q0cm6csM1"
    gas:
      enabled: true
      client_id: "muryFD4sL4XsVanqsHwX"
      client_secret: "sWYjrp0D9X7gnkHLP727SeR5lJ1MFbUpOIumN6rt6tHwExvOOJk"
      open_access_key: "5d810a147b55ca9978afa82819b9625d"
      base_url: "https://openapi.gs-robot.com"